### PR TITLE
Ingress ssl

### PR DESCRIPTION
**Pull request by batpad**
## What I am changing

See #216 - adding auto-configuration of domains and SSL for services on the cluster.

## How you can test it

This is a bit involved to test. 

Currently in the PR, I have only set this up for the `web` service, but we would want to replicate this for other services once we are happy with the setup for `web`.

To test this, you would need to:

 - Setup a new cluster
 - Follow the instructions added in this PR to set the nginx ingress controller and `cert-manager` via helm.
 - Set a value for `domain` in values.yaml . Say we set `osmseed-test.ds.io` .
 - Get the ClusterIP for the cluster by doing `kubectl get ingress` or so should give the Cluster IP
 - Create an A record for `*.osmseed-test.ds.io` to point to the cluster IP
 - Test that https://web.osmseed-test.ds.io works in the browser and that SSL is setup correctly.
 - If it does not work, one will need to check kubernetes logs to try and figure out what is failing

Once we test and manage to make this work, we should decide on a good pattern to implement this across all services.

Some considerations:

 - We should make sure it still works to deploy to `minikube` by not requiring this for a minikube install
 - Consider if we want to still allow users to specify type=LoadBalancer and handle routing and SSL themselves, and then it won't try and do any of this Ingress and SSL stuff.

@Rub21 @geohacker - let's chat about this on scrum today and see if there's a good way to try and test this, and then discuss what pattern we are happy with, and then implement the same for the rest of the services.

## Related Issues

#216

### CODE REVIEW

**Comment by batpad** [comment]
Just a quick note here:

Thinking about this, we should definitely give the users choice about how they would like services setup. So, users should be able to define something like `serviceType` in the values.yaml to specify whether services should be exposed as Load Balancers or with ClusterIP + Ingress.

This will take a little bit of thought to make not too messy, as a lot of subtle things change depending on the configuration - the way we need to setup SSL, etc.

Just a little unsure of how best to structure the options in values.yaml that users will use. Will give this a bit of consideration.

**Comment by batpad** [comment]
@Rub21 I tried adding the conditional statements to this PR for the web service - so now in values, one should be able to set `serviceType` as either `NodePort`, `ClusterIP` or `LoadBalancer` and it should do the right thing in each case.

Could you look over, and if it looks good to you, we can figure out testing this, and then applying to all the other services?

**Comment by batpad** [comment]
@Rub21 - I've added the changes to the service and ingress definitions for all the services that require it.

One thing to note: Currently, I have removed this annotation from services that might require it:

`service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "300"`

We should probably add it back for services that require it if cloudProvider is AWS and serviceType is LoadBalancer.

This involved a bit of copy-pasting - we can probably refactor this a bit using template helpers, but let's look at that after we are sure all this works.

I think next steps would be figuring out testing this, and importantly, making sure we can upgrade the OHM stack to this version of osm-seed without things breaking. For this, we would need to add `serviceType: LoadBalancer` to the OHM values.yaml, and then ideally things should work as they currently do for OHM (with the exception of the connection-idle-timeout mentioned above that we probably need to add).

I'll look into adding some better documentation, etc. for these changes.

@Rub21 could you please give this a good look and let me know if there seem to be any obvious problems? I'll give this a better look in a bit as well.

cc @geohacker

**Comment by batpad** [comment]
Next steps:

 - [x] @Rub21 to test changes on data team cluster on GCP
 - [x] If that seems to work okay, @Rub21 and @batpad test these changes on OHM staging
 - [x] If that works, merge this PR, create stable version of osm-seed
 - [x] Deploy updated stable version to both OHM and HOT instances

cc @geohacker

**Comment by batpad** [comment]
@Rub21 I added an options called `serviceAnnotations` for each of the services.

We should be able to use this to add this annotation back for services that need it and are running on AWS Load Balancer:

    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "300"

I can probably test this on the branch you have to test ohm-staging.

**Review by Rub21 — APPROVED** [review]

**Pull request merged**
