### PR TITLE
Chartpress

### PR DESCRIPTION
**Pull request by batpad**
Restructuring to use chartpress as per #164 

I'll write out detailed notes in the README on usage. The idea here would be that on Circle we would now just run `chartpress` - this will handle building images only if something has changed, and handle setting all the correct image name and tag values in the values.yaml.

I'm a bit blocked on thorough testing due to the web container not building due to some ruby errors. Will look into that, and also hook up the Circle CI integration in this branch.

@geohacker @Rub21 - the changes here are quite significant, let's discuss them, and also discuss how best we keep our different branches in sync. Once this is setup, we will have quite a clear way to move the OHM-specific changes into their own repository which treats the osm-seed Helm chart as a requirement, and contains only the over-rides required for OHM.

### CODE REVIEW

**Comment by batpad** [comment]
This PR is nearly complete. What it does so far:

 - Cleans up project structure and naming to make things more consistent, and make project easier to use with Chartpress
 - Adds a Chartpress config YAML file, specifying containers to be built and values to be modified with image tags
 - Github Action definition to run chartpress on every commit. What this does:
   - Re-builds only images where something has changed.
   - Updates values with correct tags for images
   - Publishes a Helm Chart to http://devseed.com/osm-seed-chart/

TODO:

 - Update all documentation to give examples of using `osm-seed` as a Helm chart instead of checking out Git repo, etc.
 - Create an example "deploy" repository, giving an example of using the Helm chart, over-riding needed values, etc.

cc @geohacker

**Comment by batpad** [comment]
This now has Github actions setup to rebuild images and re-publish the Helm chart on every push.

I've put some minimal documentation and a basic example on how to use the public Helm chart at https://github.com/developmentseed/osm-seed-deploy, and added a link here.

I have tested this works to install on a local Minikube setup - I needed to make some changes to the charts and default values, but mostly small things - @Rub21 - will be great if you can have a quick look.

I would recommend merging this in, and then we have a few chunks of work we can tackle as separate issues:

 - Integrate Tasking Manager and other changes into the main branch here.
 - Create a separate repository for the OHM deploy based on the `osm-seed-deploy` repo linked above
 - Improve documentation and examples overall - documentation of values.yaml, custom installs, etc.

cc @geohacker

**Comment by batpad** [comment]
Noticing some issues in the local deploy, let's hold on merging, but @Rub21 will be great if you can have a look anyway :-)

**Comment by geohacker** [comment]
This is really great @batpad! Thank you for this massive lift. All the changes look good to me and I was able to run everything using minikube and following the guide. I'm 👍  on merging this.

**Review by geohacker — APPROVED** [review]

**Pull request merged**
